---
title: "assignment2"
author: "Lucas Schiffer"
date: "October 19, 2016"
output: html_document
vignette: >
  %\VignetteIndexEntry{assignment2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(magrittr)
library(dplyr)
library(knitr)
library(ggplot2)
library(MASS)
```

## EDA
```{r, message=FALSE, warning=FALSE}
read_csv("../inst/extdata/AUdeaths_corrected_10-11-2016.csv") %>%
  glimpse()
```

## Table 2
```{r,  message=FALSE, warning=FALSE}
read_csv("../inst/extdata/AUdeaths_corrected_10-11-2016.csv") %>%
  rename(Year = year) %>% 
  mutate(rate = round(suicidetotal / personyearsatrisk * 100000, 2)) %>%
  group_by(Year) %>%
  summarise("No." = suicidetotal, "Crude Rate per 100 000 Population" =  rate) %>%
  kable(caption = "Suicide Total Deaths")
```

# Figure I
```{r, message=FALSE, warning=FALSE}
read_csv("../inst/extdata/AUdeaths_corrected_10-11-2016.csv") %>%
  rename(Year = year) %>%
  mutate(rate = suicidetotal / personyearsatrisk) %>%
  mutate(law = ifelse(Year > 1996, "> 1996", "< 1996")) %>% 
  ggplot(aes(Year, rate * 100000)) +
    geom_point(aes(colour = factor(law))) +
    geom_line(aes(colour = factor(law))) +
    geom_smooth(aes(colour = factor(law)), method = lm) +
    labs(title = "Total firearm and nonfirearm suicide deaths",
         x = "Calendar Year",
         y = "Total Suicide Deaths per 100 000 Population",
         colour = "")
```


## Model A
```{r, message=FALSE, warning=FALSE}
model_a <- read_csv("../inst/extdata/AUdeaths_corrected_10-11-2016.csv") %>%
  rename(Year = year) %>% 
  mutate(law = ifelse(Year > 1996, "> 1996", "< 1996")) %>%
  mutate(law = as.factor(law)) %>%
  filter(law == "< 1996") %>%
  glm.nb(suicidetotal ~ Year + offset(log(personyearsatrisk)), data = .)

estimate <- coef(model_a) %>% exp() %>% matrix()
estimate <- estimate[-1, , drop = FALSE]
confint <- confint(model_a) %>% exp()
confint <- confint[-1, , drop = FALSE]
cbind(estimate, confint) %>% kable(digits = 3, col.names = c("Estimate", "95% CI Lower Limit", "95% CI Upper Limit"), format.args = list(nsmall = 3, scientific = FALSE), align = "l")
```

## Model B
```{r, message=FALSE, warning=FALSE}
model_b <- read_csv("../inst/extdata/AUdeaths_corrected_10-11-2016.csv") %>%
  rename(Year = year) %>%
  mutate(law = ifelse(Year > 1996, "> 1996", "< 1996")) %>%
  mutate(law = as.factor(law)) %>%
  filter(law == "> 1996") %>%
  glm.nb(suicidetotal ~ Year + offset(log(personyearsatrisk)), data = .)

estimate <- coef(model_b) %>% exp() %>% matrix()
confint <- confint(model_b) %>% exp()
cbind(estimate, confint) %>% kable(digits = 3, col.names = c("Estimate", "95% CI Lower Limit", "95% CI Upper Limit"), format.args = list(nsmall = 3, scientific = FALSE))
```

## Model C
```{r, message=FALSE, warning=FALSE}
model_c <- read_csv("../inst/extdata/AUdeaths_corrected_10-11-2016.csv") %>%
  rename(Year = year) %>%
mutate(law = ifelse(Year > 1996, " > 1996", " < 1996")) %>%
mutate(law = as.factor(law)) %>%
mutate(Year = Year - 1996) %>%
glm.nb(suicidetotal ~ Year + law + Year * law + offset(log(personyearsatrisk)), data = .)

estimate <- coef(model_c) %>% exp() %>% matrix()
confint <- confint(model_c) %>% exp()
cbind(estimate, confint) %>% kable(digits = 3, col.names = c("Estimate", "95% CI Lower Limit", "95% CI Upper Limit"), format.args = list(nsmall = 3, scientific = FALSE))
```
